### ISSUE TITLE
user_agent

### ISSUE THREAD

**Issue by darku1337** [Zero6992/chatGPT-discord-bot#45] opened 2022-12-12 06:29 UTC
added cf_clearance

![image](https://user-images.githubusercontent.com/6857052/206976545-4051b35e-181c-4e69-9fef-261f301d6cbd.png)

**Comment by jacky-chay** [comment] 2022-12-12 06:34
![image](https://user-images.githubusercontent.com/68509767/206977210-3ea45c1f-1a5e-4bfc-9418-b7813d1e59b2.png)

you should have 4 fields inside the config.json.

**Comment by Zero6992** [comment] 2022-12-12 06:36
duplicate of #44

**Closed by Zero6992** 2022-12-12 06:36 UTC
