### ISSUE TITLE
Google Bard error

### ISSUE THREAD

**Issue by greengeckowizard** [Zero6992/chatGPT-discord-bot#374] opened 2023-04-27 21:58 UTC
Hi I get this error I'm using reply all

Google Bard encountered an error: b')]}'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n57\n[["di",136],["af.httprm",136,"-1273804148740246653",1]]\n25\n[["e",4,null,null,132]]\n'.

**Comment by Zero6992** [comment] 2023-04-28 05:45
duplicate of #358

**Closed by Zero6992** 2023-04-28 05:45 UTC
