### ISSUE TITLE
i got an error AttributeError: 'NoneType' object has no attribute 'info'

### ISSUE THREAD

**Issue by RizkyNugroho666** [Zero6992/chatGPT-discord-bot#74] opened 2022-12-16 04:24 UTC
Traceback (most recent call last):
  File "f:\Project\Python\1ntrovert Bot Remake\packages\bot.py", line 78, in send_start_prompt
    logger.info(f"Send starting prompt with size {len(prompt)}")
AttributeError: 'NoneType' object has no attribute 'info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "f:\Project\Python\1ntrovert Bot Remake\packages\bot.py", line 95, in on_ready
    await send_start_prompt(client)
  File "f:\Project\Python\1ntrovert Bot Remake\packages\bot.py", line 87, in send_start_prompt
    logger.exception(f"Error while sending starting prompt: {e}")
AttributeError: 'NoneType' object has no attribute 'exception'

**Comment by aW3ikun** [comment] 2022-12-16 07:21
I can't reproduce your errors. 
You could update the newest version using GPT-3 model with the OpenAI  API key.
Or give enough details.

**Comment by WaD45** [comment] 2022-12-16 17:32
Fully working at this time. Reset everything by creating a new one if you can

**Comment by Zero6992** [comment] 2022-12-20 18:57
Closing the issue due to lack of active

**Closed by Zero6992** 2022-12-20 18:57 UTC
