### ISSUE TITLE
Docker version of bot unable to start

### ISSUE THREAD

**Issue by JimDude7404** [Zero6992/chatGPT-discord-bot#259] opened 2023-03-18 04:00 UTC
chatgpt-discord-bot  | Traceback (most recent call last):
chatgpt-discord-bot  |   File "/DiscordBot/main.py", line 1, in <module>
chatgpt-discord-bot  |     from src import bot
chatgpt-discord-bot  |   File "/DiscordBot/src/bot.py", line 6, in <module>
chatgpt-discord-bot  |     from src import responses
chatgpt-discord-bot  |   File "/DiscordBot/src/responses.py", line 27, in <module>
chatgpt-discord-bot  |     chatbot = get_chatbot_model(CHAT_MODEL)
chatgpt-discord-bot  |   File "/DiscordBot/src/responses.py", line 25, in get_chatbot_model
chatgpt-discord-bot  |     return Chatbot(api_key=openai_api_key, engine=ENGINE)
chatgpt-discord-bot  |   File "/usr/local/lib/python3.10/site-packages/revChatGPT/V3.py", line 69, in __init__
chatgpt-discord-bot  |     if self.get_token_count("default") > self.max_tokens:
chatgpt-discord-bot  |   File "/usr/local/lib/python3.10/site-packages/revChatGPT/V3.py", line 103, in get_token_count
chatgpt-discord-bot  |     raise NotImplementedError("Unsupported engine {self.engine}")
chatgpt-discord-bot  | NotImplementedError: Unsupported engine {self.engine}
chatgpt-discord-bot exited with code 0

**Comment by Zero6992** [comment] 2023-03-18 05:44
Make sure that there is `GPT_ENGINE=“gpt-3.5-turbo”` in the `.env` file

**Comment by JimDude7404** [comment] 2023-03-18 05:45
It is the default .env file just with the token and Discord bot tokens
changed. Along with the channel IDs added

**Comment by Zero6992** [comment] 2023-03-18 06:41
What's your environment? Using VPS?

**Comment by JimDude7404** [comment] 2023-03-18 17:05
My enviroment is a dedicated server. (not a VPS). It is not blacklisted on the OpenAI API. As I can contact the API normally and even use it.

**Comment by Zero6992** [comment] 2023-03-18 17:14
`GPT-ENGINE` configuration causing this error

Make sure environment variables are set properly

**Comment by JimDude7404** [comment] 2023-03-18 17:16
They are set correctly here is my .env file

"
# Discord Bot token
DISCORD_BOT_TOKEN="REDACTED"

# Unofficial ChatGPT authentication
SESSION_TOKEN=""
OPENAI_EMAIL=""
OPENAI_PASSWORD=""

# Official GPT-3.5 authentication
OPENAI_API_KEY="REDACTED"

# Optional setting
CHAT_MODEL="OFFICIAL"
OPENAI_ENGINE="gpt-3.5-turbo"
LOGGING="True"
REPLYING_ALL="true"
DISCORD_CHANNEL_ID="REDACTED"
REPLYING_ALL_DISCORD_CHANNEL_ID="REDACTED"

**Comment by Zero6992** [comment] 2023-03-18 19:12
Not `OPENAI_ENGINE="gpt-3.5-turbo"`

Modify to `GPT_ENGINE="gpt-3.5-turbo"`

And` REPLYING_ALL="True"`  make sure the initial letter is in uppercase

**Comment by JimDude7404** [comment] 2023-03-18 19:13
Then update that SRC code to make it that by default. As it is not the
inside .env.dev

**Comment by Zero6992** [comment] 2023-03-18 19:20
I found where the issue is

The `.env.dev` in Version 1.1.1 is using an old configuration for unknown reasons, sorry about that

**Comment by Zero6992** [comment] 2023-03-18 19:20
This problem has been fixed in the Version 1.1.2

**Closed by Zero6992** 2023-03-18 19:20 UTC
