### ISSUE TITLE
How to fix this problem

### ISSUE THREAD

**Issue by jenssgeek** [Zero6992/chatGPT-discord-bot#349] opened 2023-04-16 11:49 UTC
2023-04-16 11:46:51 ERROR    discord.app_commands.tree Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "/home/runner/chatGPT-discord-bot/src/bot.py", line 32, in chat
    await client.send_message(interaction, message)
  File "/home/runner/chatGPT-discord-bot/src/aclient.py", line 58, in send_message
    author = message.author.id
AttributeError: 'Interaction' object has no attribute 'author'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/runner/chatGPT-discord-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: AttributeError: 'Interaction' object has no attribute 'author'

**Comment by Zero6992** [comment] 2023-04-27 11:49
duplicate of #230

**Closed by Zero6992** 2023-04-27 11:49 UTC
