### ISSUE TITLE
tls-client-amd64.so not found

### ISSUE THREAD

**Issue by pardeike** [Zero6992/chatGPT-discord-bot#21] opened 2022-12-09 00:28 UTC
Hi, I am trying to get this bot running on my M1 Mac. I have debian amd64 running inside UTM for Mac but I get the following error when I start the bot:

```
Traceback (most recent call last):
  File "/opt/chatGPT-discord-bot/main.py", line 1, in <module>
    from src import bot
  File "/opt/chatGPT-discord-bot/src/bot.py", line 5, in <module>
    from src import responses
  File "/opt/chatGPT-discord-bot/src/responses.py", line 1, in <module>
    from asyncChatGPT.asyncChatGPT import Chatbot
  File "/usr/local/lib/python3.9/dist-packages/asyncChatGPT/asyncChatGPT.py", line 10, in <module>
    from OpenAIAuth.OpenAIAuth import OpenAIAuth, Debugger
  File "/usr/local/lib/python3.9/dist-packages/OpenAIAuth/OpenAIAuth.py", line 5, in <module>
    import tls_client
  File "/usr/local/lib/python3.9/dist-packages/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/usr/local/lib/python3.9/dist-packages/tls_client/sessions.py", line 1, in <module>
    from .cffi import request
  File "/usr/local/lib/python3.9/dist-packages/tls_client/cffi.py", line 15, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/dist-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory
```

I checked out v0.1.2 if that matters.
Any help appreciated

**Comment by pardeike** [comment] 2022-12-09 00:34
Seems like a duplicate of #5

**Comment by Zero6992** [comment] 2022-12-09 01:06
I also have a M1 Mac on hand and I can run it normally using session token authentication, you can try it

**Comment by Zero6992** [comment] 2022-12-09 01:06
Also duplicate of #20

**Closed by Zero6992** 2022-12-09 01:06 UTC

**Comment by pardeike** [comment] 2022-12-09 07:14
> I also have a M1 Mac on hand and I can run it normally using session token authentication, you can try it

I am using a session token. What are you doing differently?

**Comment by Zero6992** [comment] 2022-12-09 07:41
> > I also have a M1 Mac on hand and I can run it normally using session token authentication, you can try it
> 
> I am using a session token. What are you doing differently?

I am running on the M1, not in a VM

**Comment by pardeike** [comment] 2022-12-09 07:56
Oh, that makes things much easier. Didn’t even think it would work. I’ll try.

**Comment by pardeike** [comment] 2022-12-09 09:46
Ok, works great. May I ask how to connect it to my discord? The readme isn't very detailed and this is my first bot. Most bots seems have their own webpage and/or you should invite it. Not sure how to start.

**Comment by pardeike** [comment] 2022-12-09 09:52
Nevermind. Need to use the url of the URL Generator too. Stupid me.
