### ISSUE TITLE
docker environment, compiled last night works fine, this morning I can't send the message, pulling the new code reports an error

### ISSUE THREAD

**Issue by GeekWorkCode** [Zero6992/chatGPT-discord-bot#69] opened 2022-12-15 05:04 UTC
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src import bot
  File "/DiscordBot/src/bot.py", line 3, in <module>
    from src import responses
  File "/DiscordBot/src/responses.py", line 32, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/revChatGPT.py", line 116, in __init__
    self.refresh_session()
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/revChatGPT.py", line 295, in refresh_session
    asyncio.run(self.get_cf_cookies())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/revChatGPT.py", line 390, in get_cf_cookies
    raise Exception("cf challenge fail")
Exception: cf challenge fail

**Comment by aW3ikun** [comment] 2022-12-15 05:08
duplicate of #67.

**Comment by Zero6992** [comment] 2022-12-15 12:45
refer #68

**Comment by Zero6992** [comment] 2022-12-15 21:48
Change to Using OpenAI official GPT-3 API now

**Closed by Zero6992** 2022-12-15 21:48 UTC
