### ISSUE TITLE
Unable to use /chat command

### ISSUE THREAD

**Issue by JimDude7404** [Zero6992/chatGPT-discord-bot#256] opened 2023-03-17 19:40 UTC
Version: 1.1.1
Linux Version: 5.15
Python Version: 3.10
All requirements met since they are installed automatically

The issue I am having is:

2023-03-17 15:38:11 INFO     src.bot -> JimSh1m#7404 : /chat [hi] in (├・talk-to-bot)
2023-03-17 15:38:11 ERROR    discord.app_commands.tree Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "/home/container/discord/app_commands/commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "/home/container/src/bot.py", line 152, in chat
    await send_message(interaction, message)
  File "/home/container/src/bot.py", line 30, in send_message
    author = message.author.id
AttributeError: 'Interaction' object has no attribute 'author'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/discord/app_commands/tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/container/discord/app_commands/commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/container/discord/app_commands/commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: AttributeError: 'Interaction' object has no attribute 'author'

**Comment by ryanshrott** [comment] 2023-03-17 19:50
same issue, how to fix it?

**Comment by Zero6992** [comment] 2023-03-18 03:44
duplicate of #230

**Closed** 2023-03-18 03:44 UTC

**Comment by JimDude7404** [comment] 2023-03-18 03:49
Hello I am using the official API so the place that you said this is a duplicate of is unrelated.

**Comment by Zero6992** [comment] 2023-03-18 05:38
It's the same issue and it's not related to the chat-model

**Comment by Zero6992** [comment] 2023-03-18 11:42
> So what's the solution. Still confused.

You could try the solutions mentioned in the thread about this issue. 

I can't reproduce this error, making it difficult for me to fix. I believe it may be related to desktop environment

**Comment by JimDude7404** [comment] 2023-03-18 11:50
It cannot be related to the desktop environment because I have tested it
across multiple devices and multiple LXC containers.

**Comment by ryanshrott** [comment] 2023-03-18 12:04
Fixed. Missing environment variables. Look at .env.example.

**Comment by Zero6992** [comment] 2023-03-18 12:16
> It cannot be related to the desktop environment because I have tested it across multiple devices and multiple LXC containers.

That's weird. I have tested it on Windows, Mac OS, and Linux VPS, and everything is running normally to me
