### ISSUE TITLE
AttributeError: type object 'Completion' has no attribute 'acreate'

### ISSUE THREAD

**Issue by doctorsax** [Zero6992/chatGPT-discord-bot#195] opened 2023-02-21 16:25 UTC
I have an error when starting and also when I make a request on discord :

```
2023-02-21 17:23:25 ERROR    src.bot -> Error while sending starting prompt: type object 'Completion' has no attribute 'acreate'
Traceback (most recent call last):
  File "/root/chatGPT-discord-bot/src/bot.py", line 108, in send_start_prompt
    responseMessage = await responses.handle_response(prompt)
  File "/root/chatGPT-discord-bot/src/responses.py", line 11, in handle_response
    response = await chatbot.ask(message)
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/Official.py", line 232, in ask
    completion = await self._get_completion(
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/Official.py", line 213, in _get_completion
    return await openai.Completion.acreate(
AttributeError: type object 'Completion' has no attribute 'acreate'
```
![image](https://user-images.githubusercontent.com/65809145/220402352-14e6c290-11d3-4c5b-8728-21208c88b793.png)

**Comment by Zero6992** [comment] 2023-02-23 05:37
duplicate of #151

**Closed by Zero6992** 2023-02-23 05:37 UTC
