### ISSUE TITLE
Issue on new codes

### ISSUE THREAD

**Issue by TaijiMonster** [Zero6992/chatGPT-discord-bot#180] opened 2023-02-12 02:36 UTC
2023-02-12T02:35:58.444047815Z [2023-02-12 02:35:58] [INFO    ] discord.client: logging in using static token
2023-02-12T02:35:59.775870035Z Traceback (most recent call last):
2023-02-12T02:35:59.775893900Z   File "/DiscordBot/main.py", line 30, in <module>
2023-02-12T02:35:59.775900041Z     bot.run_discord_bot()
2023-02-12T02:35:59.775901724Z   File "/DiscordBot/src/bot.py", line 212, in run_discord_bot
2023-02-12T02:35:59.775994157Z     client.run(TOKEN)
2023-02-12T02:35:59.776014626Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 828, in run
2023-02-12T02:35:59.776146864Z     asyncio.run(runner())
2023-02-12T02:35:59.776151403Z   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2023-02-12T02:35:59.776167553Z     return loop.run_until_complete(main)
2023-02-12T02:35:59.776175648Z   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2023-02-12T02:35:59.776294391Z     return future.result()
2023-02-12T02:35:59.776297948Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 817, in runner
2023-02-12T02:35:59.776412652Z     await self.start(token, reconnect=reconnect)
2023-02-12T02:35:59.776418964Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 746, in start
2023-02-12T02:35:59.776528019Z     await self.connect(reconnect=reconnect)
2023-02-12T02:35:59.776537086Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 672, in connect
2023-02-12T02:35:59.776665898Z     raise PrivilegedIntentsRequired(exc.shard_id) from None
2023-02-12T02:35:59.776670627Z discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
2023-02-12T02:36:07.160813900Z [2023-02-12 02:36:07] [INFO    ] discord.client: logging in using static token
2023-02-12T02:36:08.483237404Z Traceback (most recent call last):
2023-02-12T02:36:08.483266949Z   File "/DiscordBot/main.py", line 30, in <module>
2023-02-12T02:36:08.483273612Z     bot.run_discord_bot()
2023-02-12T02:36:08.483275836Z   File "/DiscordBot/src/bot.py", line 212, in run_discord_bot
2023-02-12T02:36:08.483366903Z     client.run(TOKEN)
2023-02-12T02:36:08.483375379Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 828, in run
2023-02-12T02:36:08.483529262Z     asyncio.run(runner())
2023-02-12T02:36:08.483537747Z   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2023-02-12T02:36:08.483573775Z     return loop.run_until_complete(main)
2023-02-12T02:36:08.483582982Z   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2023-02-12T02:36:08.483727854Z     return future.result()
2023-02-12T02:36:08.483734236Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 817, in runner
2023-02-12T02:36:08.483869619Z     await self.start(token, reconnect=reconnect)
2023-02-12T02:36:08.483877945Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 746, in start
2023-02-12T02:36:08.484000856Z     await self.connect(reconnect=reconnect)
2023-02-12T02:36:08.484006065Z   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 672, in connect
2023-02-12T02:36:08.484116883Z     raise PrivilegedIntentsRequired(exc.shard_id) from None
2023-02-12T02:36:08.484122223Z discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by TaijiMonster** [comment] 2023-02-12 02:38
Without using docker also giving error:

 python3 main.py
[2023-02-12 10:37:03] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    bot.run_discord_bot()
  File "C:\Users\lw\Documents\lwloo\chatgptbot\src\bot.py", line 212, in run_discord_bot
    client.run(TOKEN)
  File "C:\Users\lw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\lw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\lw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 746, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\lw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 672, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014E7B8A7940>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Zero6992** [comment] 2023-02-12 09:49
duplicate of #164

**Closed by Zero6992** 2023-02-12 09:49 UTC
